### PR TITLE
Update Sony - PlayStation Portable (Redump).json

### PR DESCRIPTION
**Pull request by rufotheone-fr**
As I said earlier:
In fact, God Eater (the first edition of the game) was released exclusively in Japan with added content through "God Eater Burst - Append-ban". Later, Gods Eater: Burst was released worldwide (including Japan) with God Eater + Burst content, so I though that God Eater and the Burst - Append-ban were useless.

### CODE REVIEW

**Comment by unexpectedpanda** [comment]
Ah right, I see where you're coming from. I also misunderstood the relationship between the _Append-ban_ and the original version.

There are a few ways of achieving the same thing in Retool. For removes, I usually try not to use them unless there's no other way (usually related to compilations). If titles can be grouped together, it makes it easier to track things in the future.

In this case I'd use this method instead:

```
"God Eater": [
			["Gods Eater Burst", 0],
			["God Eater Burst", 0]
		],
"God Eater Burst - Append-ban": [
			["Gods Eater Burst", 0],
			["God Eater Burst", 0]
		],
```

You'll still get the same end result.

**Comment by rufotheone-fr** [comment]
For removes, I usually try not to use them unless there's no other way (usually related to compilations).

That's what I've understood and, in my mind, God Eater Burst = compilation of God Eater + Burst Append-ban ^^

**Comment by unexpectedpanda** [comment]
Ah interesting perspective :) I think of a compilation as a group of standalone titles. Append-ban was pretty much an expansion pack from what I can see that required the original disc, bringing the original up to parity with the _Burst_ edition. As such to my mind, it's more like:

God Eater: Original
Append-ban: DLC
Gods Eater Burst: Special edition that includes DLC.

**Comment by rufotheone-fr** [comment]
Ok let's go with your solution.
Thanks UP !

**Pull request merged**
