### PR TITLE
Update Sony - PlayStation 2.json

### PR DESCRIPTION
**Pull request by rufotheone-fr**

### CODE REVIEW

**Comment by rufotheone-fr** [comment]
OK, we have something to do about various KoF titles :

"NeoGeo Online Collection Vol. 3 - The King of Fighters - Orochi" (KoF 95/96/97) which is fine for jap audience but is superseded by "King of Fighters Collection, The - The Orochi Saga" (KoF 94/95/96/97/98)

"NeoGeo Online Collection Vol. 7 - The King of Fighters - Nests" (KoF 99 Evolution/2000/2001) which is fine to have for everyone because it's the only way to get KoF 99 Evo BUT it doubles KoF 2K/2K1 for jap audience

**Comment by rufotheone-fr** [comment]
And I cant' get "Persona 3 FES" to properly replace "Persona 3" and have the correct region selected (I want PAL region first).
So I have reverted the list to get proper P3 + P3 FES while I'm trying to get it working the right way u_u

**Comment by unexpectedpanda** [comment]
Finally jumping on this, way too late!

> And I cant' get "Persona 3 FES" to properly replace "Persona 3" and have the correct region selected (I want PAL region first). So I have reverted the list to get proper P3 + P3 FES while I'm trying to get it working the right way u_u

Ah, a few questions here.

1. Why do you want the PAL version?
2. Is Europe higher than USA in your region order?

I might have to check a few things in the code to see what's going on.

>OK, we have something to do about various KoF titles :
>
> "NeoGeo Online Collection Vol. 3 - The King of Fighters - Orochi" (KoF 95/96/97) which is fine for jap audience but is superseded by "King of Fighters Collection, The - The Orochi Saga" (KoF 94/95/96/97/98)

> "NeoGeo Online Collection Vol. 7 - The King of Fighters - Nests" (KoF 99 Evolution/2000/2001) which is fine to have for everyone because it's the only way to get KoF 99 Evo BUT it doubles KoF 2K/2K1 for jap audience

😭 Always compilations breaking things. I don't think you're going to get anything perfect here. Let's see...

* _King of Fighters Collection, The - The Orochi Saga_ can be a zero priority title of _NeoGeo Online Collection Vol. 3 - The King of Fighters - Orochi_, since it's a superset.
* We have to keep _King of Fighters '98, The - Ultimate Match (USA)_ and _(Europe)_, as only the regular _'98_ is in _King of Fighters Collection, The - The Orochi Saga_ in either region.
* We need to remove _King of Fighters 2000, The (Japan)_ and _King of Fighters 2000, The (USA)_ if Japan is a higher region than USA.
* We need to remove _King of Fighters 2001, The (Japan)_ and _King of Fighters 2001, The (Korea)_ if Japan is a higher region than USA or Korea.

This looks like new functionality is needed to me, a conditional remove. Or at least the ability to remove from within a conditional override. I'm tempted to implement that in Retool v2 though, and leave v1 where it is in terms of functionality.

**Comment by unexpectedpanda** [comment]
I'm going to merge this in now, but I'll have a chat with you on Discord just so you don't miss the replies :)

**Pull request merged**
